name: Terraform CI Check

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [day1, day2, day3, day4]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ matrix.folder }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ matrix.folder }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.folder }}
        run: terraform plan -input=false || true